def _submit(self):
    self.authenticate()
    title = 'HelpMe UserVoice Ticket: %s' % self.run_id
    body = self.data['user_prompt_issue']
    envars = self.data.get('record_environment')
    if envars not in [None, '', []]:
        body += '\n\nEnvironment:\n'
        for envar in envars:
            body += ' - %s: %s\n' % (envar[0], envar[1])
    asciinema = self.data.get('record_asciinema')
    if asciinema not in [None, '']:
        url = upload_asciinema(asciinema)
        if url is not None:
            body += '\n\nAsciinema Recording: %s' % url
    body += '\ngenerated by HelpMe: https://vsoch.github.io/helpme/'
    self.post_ticket(title, body)