def WriteSetupPy(self, out):
    printer = self._GetPrinter(out)
    year = datetime.datetime.now().year
    printer('# Copyright %s Google Inc. All Rights Reserved.' % year)
    printer('#')
    printer('# Licensed under the Apache License, Version 2.0 (the"License");')
    printer(
        '# you may not use this file except in compliance with the License.')
    printer('# You may obtain a copy of the License at')
    printer('#')
    printer('#   http://www.apache.org/licenses/LICENSE-2.0')
    printer('#')
    printer(
        '# Unless required by applicable law or agreed to in writing, software'
        )
    printer(
        '# distributed under the License is distributed on an "AS IS" BASIS,')
    printer(
        '# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
        )
    printer(
        '# See the License for the specific language governing permissions and'
        )
    printer('# limitations under the License.')
    printer()
    printer('import setuptools')
    printer('REQUIREMENTS = [')
    with printer.Indent(indent='    '):
        parts = self.apitools_version.split('.')
        major = parts.pop(0)
        minor = parts.pop(0)
        printer('"google-apitools>=%s,~=%s.%s",', self.apitools_version,
            major, minor)
        printer('"httplib2>=0.9",')
        printer('"oauth2client>=1.4.12",')
    printer(']')
    printer('_PACKAGE = "apitools.clients.%s"' % self.__package)
    printer()
    printer('setuptools.setup(')
    with printer.Indent(indent='    '):
        printer('name="google-apitools-%s-%s",', self.__package, self.__version
            )
        printer('version="%s.%s",', self.apitools_version, self.__revision)
        printer('description="Autogenerated apitools library for %s",' % (
            self.__package,))
        printer('url="https://github.com/google/apitools",')
        printer('author="Craig Citro",')
        printer('author_email="craigcitro@google.com",')
        printer('packages=setuptools.find_packages(),')
        printer('install_requires=REQUIREMENTS,')
        printer('classifiers=[')
        with printer.Indent(indent='    '):
            printer('"Programming Language :: Python :: 2.7",')
            printer('"License :: OSI Approved :: Apache Software License",')
        printer('],')
        printer('license="Apache 2.0",')
        printer('keywords="apitools apitools-%s %s",' % (self.__package,
            self.__package))
    printer(')')