def generate_module_table_header(modules):
    mod_defs = []
    print('// Automatically generated by makemoduledefs.py.\n')
    for module_name, obj_module, enabled_define in modules:
        mod_def = 'MODULE_DEF_{}'.format(module_name.upper())
        mod_defs.append(mod_def)
        print(
            """#if ({enabled_define})
    extern const struct _mp_obj_module_t {obj_module};
    #define {mod_def} {{ MP_ROM_QSTR({module_name}), MP_ROM_PTR(&{obj_module}) }},
#else
    #define {mod_def}
#endif
"""
            .format(module_name=module_name, obj_module=obj_module,
            enabled_define=enabled_define, mod_def=mod_def))
    print('\n#define MICROPY_REGISTERED_MODULES \\')
    for mod_def in mod_defs:
        print('    {mod_def} \\'.format(mod_def=mod_def))
    print('// MICROPY_REGISTERED_MODULES')