def _write_unassigned_ranges(out_filename):
    with open(out_filename, 'wt') as f:
        f.write('# auto-generated by port_for._download_ranges (%s)\n' %
            datetime.date.today())
        f.write('UNASSIGNED_RANGES = [\n')
        for range in to_ranges(sorted(list(_unassigned_ports()))):
            f.write('    (%d, %d),\n' % range)
        f.write(']\n')