def _submit(self):
    body = self.data['user_prompt_issue']
    title = self.data['user_prompt_title']
    repo = self.data['user_prompt_repo']
    envars = self.data.get('record_environment')
    body = body + envars_to_markdown(envars)
    asciinema = self.data.get('record_asciinema')
    if asciinema not in [None, '']:
        url = upload_asciinema(asciinema)
        if url is not None:
            body += '\n[View Asciinema Recording](%s)' % url
    body += '\n\ngenerated by [HelpMe](https://vsoch.github.io/helpme/)'
    body += '\nHelpMe Github Issue: %s' % self.run_id
    issue = create_issue(title, body, repo, self.token)
    return issue